from abc import ABC, abstractmethod
from typing import Dict
from core.domain.models.league import League

class LeagueRepository(ABC):
    @abstractmethod
    def save_league(self, league: League) -> None: ...
    @abstractmethod
    def get_league(self, league_id: str) -> League | None: ...
    @abstractmethod
    def get_all_leagues(self) -> Dict[str, League]: ...
    @abstractmethod
    def list_leagues(self) -> list[League]: ...
    @abstractmethod
    def delete_league(self, league_id: str) -> None: ...